
export const COUNTRY_CODE_TO_NAME: Record<string, string> = {
  GB: "United Kingdom",
  IE: "Ireland",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  PT: "Portugal",
  NL: "Netherlands",
  BE: "Belgium",
  CH: "Switzerland",
  AT: "Austria",
  DK: "Denmark",
  SE: "Sweden",
  NO: "Norway",
  FI: "Finland",
  PL: "Poland",
  CZ: "Czech Republic",
  SK: "Slovakia",
  HU: "Hungary",
  RO: "Romania",
  BG: "Bulgaria",
  GR: "Greece",
  HR: "Croatia",
  SI: "Slovenia",
  UA: "Ukraine",
  RU: "Russia",
  TR: "Turkey",
  IS: "Iceland",
  LU: "Luxembourg",
  MT: "Malta",
  CY: "Cyprus",
  LV: "Latvia",
  LT: "Lithuania",
  EE: "Estonia",
  AX: "Åland Islands",
  GI: "Gibraltar",
  IM: "Isle of Man",
  JE: "Jersey",
  GG: "Guernsey",
  MC: "Monaco",
  LI: "Liechtenstein",
  SM: "San Marino",
  VA: "Vatican",
  AD: "Andorra",
  ME: "Montenegro",
  MK: "North Macedonia",
  BA: "Bosnia and Herzegovina",
  RS: "Serbia",
  XK: "Kosovo",

  CN: "China",
  JP: "Japan",
  KR: "South Korea",
  TW: "Taiwan",
  HK: "Hong Kong",
  MO: "Macau",
  IN: "India",
  PK: "Pakistan",
  BD: "Bangladesh",
  LK: "Sri Lanka",
  NP: "Nepal",
  BT: "Bhutan",
  TH: "Thailand",
  MY: "Malaysia",
  SG: "Singapore",
  ID: "Indonesia",
  PH: "Philippines",
  VN: "Vietnam",
  KH: "Cambodia",
  LA: "Laos",
  MM: "Myanmar",
  BN: "Brunei",
  TL: "East Timor",
  KZ: "Kazakhstan",
  UZ: "Uzbekistan",
  TM: "Turkmenistan",
  TJ: "Tajikistan",
  KG: "Kyrgyzstan",
  AF: "Afghanistan",
  IR: "Iran",
  IQ: "Iraq",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  QA: "Qatar",
  BH: "Bahrain",
  KW: "Kuwait",
  OM: "Oman",
  YE: "Yemen",
  JO: "Jordan",
  IL: "Israel",
  PS: "Palestine",
  LB: "Lebanon",
  SY: "Syria",
  AM: "Armenia",
  AZ: "Azerbaijan",
  GE: "Georgia",

  US: "United States",
  CA: "Canada",
  MX: "Mexico",
  BR: "Brazil",
  AR: "Argentina",
  CL: "Chile",
  CO: "Colombia",
  PE: "Peru",
  VE: "Venezuela",
  EC: "Ecuador",
  BO: "Bolivia",
  PY: "Paraguay",
  UY: "Uruguay",
  GY: "Guyana",
  SR: "Suriname",
  GF: "French Guiana",
  CR: "Costa Rica",
  PA: "Panama",
  GT: "Guatemala",
  SV: "El Salvador",
  HN: "Honduras",
  NI: "Nicaragua",
  BZ: "Belize",
  CU: "Cuba",
  DO: "Dominican Republic",
  HT: "Haiti",
  JM: "Jamaica",
  TT: "Trinidad and Tobago",
  BS: "Bahamas",
  BB: "Barbados",
  VC: "Saint Vincent",
  LC: "Saint Lucia",
  AG: "Antigua and Barbuda",
  DM: "Dominica",
  GD: "Grenada",
  KN: "Saint Kitts and Nevis",
  AI: "Anguilla",
  VG: "British Virgin Islands",
  VI: "US Virgin Islands",
  PR: "Puerto Rico",
  GL: "Greenland",

  EG: "Egypt",
  ZA: "South Africa",
  NG: "Nigeria",
  KE: "Kenya",
  ET: "Ethiopia",
  GH: "Ghana",
  CI: "Ivory Coast",
  UG: "Uganda",
  TZ: "Tanzania",
  MA: "Morocco",
  TN: "Tunisia",
  DZ: "Algeria",
  LY: "Libya",
  SD: "Sudan",
  SN: "Senegal",
  BW: "Botswana",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  MW: "Malawi",
  MZ: "Mozambique",
  AO: "Angola",
  NA: "Namibia",
  GA: "Gabon",
  CG: "Republic of the Congo",
  CD: "Democratic Republic of the Congo",
  CM: "Cameroon",
  BF: "Burkina Faso",
  ML: "Mali",
  NE: "Niger",
  TD: "Chad",
  CF: "Central African Republic",
  RW: "Rwanda",
  BI: "Burundi",
  SC: "Seychelles",
  MG: "Madagascar",
  MU: "Mauritius",
  RE: "Réunion",
  GN: "Guinea",
  GW: "Guinea-Bissau",
  SL: "Sierra Leone",
  LR: "Liberia",
  ER: "Eritrea",
  DJ: "Djibouti",
  SO: "Somalia",
  MR: "Mauritania",
  CV: "Cape Verde",
  ST: "São Tomé and Príncipe",
  KM: "Comoros",

  AU: "Australia",
  NZ: "New Zealand",
  FJ: "Fiji",
  PG: "Papua New Guinea",
  SB: "Solomon Islands",
  VU: "Vanuatu",
  WS: "Samoa",
  KI: "Kiribati",
  TO: "Tonga",
  PW: "Palau",
  FM: "Micronesia",
  MH: "Marshall Islands",
  NR: "Nauru",
  TV: "Tuvalu",
  PF: "French Polynesia",
  NC: "New Caledonia",
  GU: "Guam",
  MP: "Northern Mariana Islands",
  AS: "American Samoa",
  CK: "Cook Islands",
  NU: "Niue",

  EU: "European Union (Regional)",
  RG: "Regional",
};

export const COUNTRY_NAME_TO_CODE: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_CODE_TO_NAME).map(([code, name]) => [
    name.toLowerCase(),
    code,
  ]),
);

export function getCountryName(countryCode: string | undefined): string {
  if (!countryCode) return "Unknown";
  return COUNTRY_CODE_TO_NAME[countryCode.toUpperCase()] || countryCode;
}

export function getCountryCode(countryName: string | undefined): string | null {
  if (!countryName) return null;
  return COUNTRY_NAME_TO_CODE[countryName.toLowerCase()] || null;
}

export function getAllCountries(): Array<{ code: string; name: string }> {
  return Object.entries(COUNTRY_CODE_TO_NAME)
    .filter(([code]) => !["NA", "GL", "RG", "EU"].includes(code))
    .map(([code, name]) => ({ code, name }))
    .sort((a, b) => a.name.localeCompare(b.name));
}

export function searchCountries(
  query: string,
): Array<{ code: string; name: string }> {
  const lowerQuery = query.toLowerCase();
  return getAllCountries().filter(
    (country) =>
      country.name.toLowerCase().includes(lowerQuery) ||
      country.code.toLowerCase().includes(lowerQuery),
  );
}
