
export enum Region {
  AFRICA = 'Africa',
  ASIA = 'Asia',
  CARIBBEAN = 'Caribbean Islands',
  EUROPE = 'Europe',
  EU_UK = 'European Union and United Kingdom',
  LATIN_AMERICA = 'Latin America',
  MIDDLE_EAST_NA = 'Middle East and North Africa',
  NORTH_AMERICA = 'North America',
  OCEANIA = 'Oceania',
}

export const COUNTRY_TO_REGION: Record<string, Region> = {
  DZ: Region.MIDDLE_EAST_NA, 
  AO: Region.AFRICA, 
  BJ: Region.AFRICA, 
  BW: Region.AFRICA, 
  BF: Region.AFRICA,  
  BI: Region.AFRICA,  
  CM: Region.AFRICA,  
  CV: Region.AFRICA, 
  CF: Region.AFRICA,  
  TD: Region.AFRICA, 
  KM: Region.AFRICA, 
  CG: Region.AFRICA, 
  CD: Region.AFRICA, 
  CI: Region.AFRICA,  
  DJ: Region.AFRICA, 
  EG: Region.MIDDLE_EAST_NA, 
  GQ: Region.AFRICA, 
  ER: Region.AFRICA, 
  SZ: Region.AFRICA, 
  ET: Region.AFRICA, 
  GA: Region.AFRICA, 
  GM: Region.AFRICA, 
  GH: Region.AFRICA, 
  GN: Region.AFRICA, 
  GW: Region.AFRICA, 
  KE: Region.AFRICA, 
  LS: Region.AFRICA, 
  LR: Region.AFRICA, 
  LY: Region.MIDDLE_EAST_NA, 
  MG: Region.AFRICA, 
  MW: Region.AFRICA, 
  ML: Region.AFRICA, 
  MR: Region.MIDDLE_EAST_NA, 
  MU: Region.AFRICA, 
  MA: Region.MIDDLE_EAST_NA, 
  MZ: Region.AFRICA, 
  NA: Region.AFRICA, 
  NE: Region.AFRICA, 
  NG: Region.AFRICA, 
  RW: Region.AFRICA, 
  ST: Region.AFRICA, 
  SN: Region.AFRICA, 
  SC: Region.AFRICA, 
  SL: Region.AFRICA,  
  SO: Region.AFRICA, 
  ZA: Region.AFRICA,  
  SS: Region.AFRICA,  
  SD: Region.MIDDLE_EAST_NA, 
  TZ: Region.AFRICA, 
  TG: Region.AFRICA, 
  TN: Region.MIDDLE_EAST_NA, 
  UG: Region.AFRICA, 
  ZM: Region.AFRICA, 
  ZW: Region.AFRICA, 

  AF: Region.ASIA, 
  AM: Region.MIDDLE_EAST_NA, 
  AZ: Region.MIDDLE_EAST_NA, 
  BH: Region.MIDDLE_EAST_NA, 
  BD: Region.ASIA, 
  BT: Region.ASIA, 
  BN: Region.ASIA, 
  KH: Region.ASIA, 
  CN: Region.ASIA, 
  GE: Region.MIDDLE_EAST_NA, 
  HK: Region.ASIA, 
  IN: Region.ASIA, 
  ID: Region.ASIA, 
  IR: Region.MIDDLE_EAST_NA, 
  IQ: Region.MIDDLE_EAST_NA, 
  IL: Region.MIDDLE_EAST_NA, 
  JP: Region.ASIA, 
  JO: Region.MIDDLE_EAST_NA, 
  KZ: Region.ASIA, 
  KW: Region.MIDDLE_EAST_NA, 
  KG: Region.ASIA, 
  LA: Region.ASIA, 
  LB: Region.MIDDLE_EAST_NA, 
  MO: Region.ASIA, 
  MY: Region.ASIA, 
  MV: Region.ASIA, 
  MN: Region.ASIA, 
  MM: Region.ASIA, 
  NP: Region.ASIA, 
  KP: Region.ASIA, 
  OM: Region.MIDDLE_EAST_NA, 
  PK: Region.ASIA, 
  PS: Region.MIDDLE_EAST_NA, 
  PH: Region.ASIA, 
  QA: Region.MIDDLE_EAST_NA, 
  SA: Region.MIDDLE_EAST_NA, 
  SG: Region.ASIA, 
  KR: Region.ASIA, 
  LK: Region.ASIA, 
  SY: Region.MIDDLE_EAST_NA, 
  TW: Region.ASIA, 
  TJ: Region.ASIA, 
  TH: Region.ASIA, 
  TL: Region.ASIA,
  TR: Region.MIDDLE_EAST_NA, 
  TM: Region.ASIA, 
  AE: Region.MIDDLE_EAST_NA,
  UZ: Region.ASIA, 
  VN: Region.ASIA, 
  YE: Region.MIDDLE_EAST_NA, 

  AG: Region.CARIBBEAN, 
  BS: Region.CARIBBEAN, 
  BB: Region.CARIBBEAN, 
  BZ: Region.CARIBBEAN, 
  KY: Region.CARIBBEAN, 
  CR: Region.CARIBBEAN, 
  CU: Region.CARIBBEAN, 
  DM: Region.CARIBBEAN, 
  DO: Region.CARIBBEAN, 
  SV: Region.CARIBBEAN, 
  GD: Region.CARIBBEAN, 
  GT: Region.CARIBBEAN, 
  HT: Region.CARIBBEAN, 
  HN: Region.CARIBBEAN, 
  JM: Region.CARIBBEAN, 
  NI: Region.CARIBBEAN, 
  PA: Region.CARIBBEAN, 
  KN: Region.CARIBBEAN,  
  LC: Region.CARIBBEAN, 
  VC: Region.CARIBBEAN, 
  TT: Region.CARIBBEAN, 

  AL: Region.EUROPE, 
  AD: Region.EUROPE, 
  AT: Region.EUROPE, 
  BY: Region.EUROPE, 
  BE: Region.EU_UK, 
  BA: Region.EUROPE, 
  BG: Region.EU_UK, 
  HR: Region.EU_UK, 
  CY: Region.EU_UK, 
  CZ: Region.EU_UK, 
  DK: Region.EU_UK, 
  EE: Region.EU_UK, 
  FI: Region.EU_UK, 
  FR: Region.EU_UK, 
  DE: Region.EU_UK, 
  GR: Region.EU_UK, 
  HU: Region.EU_UK, 
  IS: Region.EUROPE, 
  IE: Region.EU_UK, 
  IT: Region.EU_UK, 
  XK: Region.EUROPE, 
  LV: Region.EU_UK, 
  LI: Region.EUROPE, 
  LT: Region.EU_UK, 
  LU: Region.EU_UK, 
  MT: Region.EU_UK, 
  MD: Region.EUROPE, 
  MC: Region.EUROPE, 
  ME: Region.EUROPE, 
  NL: Region.EU_UK, 
  MK: Region.EUROPE, 
  NO: Region.EUROPE, 
  PL: Region.EU_UK, 
  PT: Region.EU_UK, 
  RO: Region.EU_UK, 
  RU: Region.EUROPE, 
  SM: Region.EUROPE, 
  RS: Region.EUROPE, 
  SK: Region.EU_UK, 
  SI: Region.EU_UK, 
  ES: Region.EU_UK, 
  SE: Region.EU_UK, 
  CH: Region.EUROPE, 
  UA: Region.EUROPE, 
  GB: Region.EU_UK, 
  VA: Region.EUROPE, 

  AR: Region.LATIN_AMERICA, 
  BO: Region.LATIN_AMERICA, 
  BR: Region.LATIN_AMERICA, 
  CL: Region.LATIN_AMERICA, 
  CO: Region.LATIN_AMERICA, 
  EC: Region.LATIN_AMERICA, 
  GF: Region.LATIN_AMERICA, 
  GY: Region.LATIN_AMERICA, 
  PY: Region.LATIN_AMERICA, 
  PE: Region.LATIN_AMERICA, 
  SR: Region.LATIN_AMERICA, 
  UY: Region.LATIN_AMERICA, 
  VE: Region.LATIN_AMERICA, 

  EH: Region.MIDDLE_EAST_NA, 

  CA: Region.NORTH_AMERICA, 
  MX: Region.NORTH_AMERICA, 
  US: Region.NORTH_AMERICA, 

  
  AU: Region.OCEANIA, 
  FJ: Region.OCEANIA, 
  KI: Region.OCEANIA, 
  MH: Region.OCEANIA, 
  FM: Region.OCEANIA, 
  NR: Region.OCEANIA, 
  NZ: Region.OCEANIA, 
  PW: Region.OCEANIA, 
  PG: Region.OCEANIA, 
  WS: Region.OCEANIA, 
  SB: Region.OCEANIA, 
  TO: Region.OCEANIA, 
  TV: Region.OCEANIA, 
  VU: Region.OCEANIA, 
};
export const getRegionForCountry = (countryCode: string): Region | null => {
  return COUNTRY_TO_REGION[countryCode.toUpperCase()] || null;
};
export const getAllRegions = (): Region[] => {
  return Object.values(Region);
};
export const getCountriesInRegion = (region: Region): string[] => {
  return Object.entries(COUNTRY_TO_REGION)
    .filter(([, r]) => r === region)
    .map(([code]) => code);
};
