export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  NOT_MODIFIED: 304,
  TEMPORARY_REDIRECT: 307,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;
export const ERROR_CODES = {
  INVALID_INPUT: 'ERR_INVALID_INPUT',
  MISSING_FIELD: 'ERR_MISSING_FIELD',
  INVALID_FORMAT: 'ERR_INVALID_FORMAT',

  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  TOKEN_INVALID: 'ERR_TOKEN_INVALID',

  FORBIDDEN: 'ERR_FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'ERR_INSUFFICIENT_PERMISSIONS',

  NOT_FOUND: 'ERR_NOT_FOUND',
  ALREADY_EXISTS: 'ERR_ALREADY_EXISTS',
  CONFLICT: 'ERR_CONFLICT',

  PAYMENT_FAILED: 'ERR_PAYMENT_FAILED',
  ORDER_INVALID: 'ERR_ORDER_INVALID',
  ESIM_UNAVAILABLE: 'ERR_ESIM_UNAVAILABLE',

  EXTERNAL_API_ERROR: 'ERR_EXTERNAL_API_ERROR',
  EXTERNAL_API_TIMEOUT: 'ERR_EXTERNAL_API_TIMEOUT',

  INTERNAL_ERROR: 'ERR_INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'ERR_SERVICE_UNAVAILABLE',

  NETWORK_ERROR: 'ERR_NETWORK_ERROR',
  REQUEST_TIMEOUT: 'ERR_REQUEST_TIMEOUT',
} as const;
export const TOAST_TYPES = {
  SUCCESS: 'success',
  ERROR: 'error',
  WARNING: 'warning',
  INFO: 'info',
} as const;
export const REQUEST_TIMEOUT = 30000;
export const RETRY_CONFIG = {
  max_attempts: 3,
  initial_delay_ms: 1000,
  max_delay_ms: 10000,
  backoff_multiplier: 2,
} as const;
