export const HTTP_STATUS = {
  OK: 200,
  CREATED: 201,
  ACCEPTED: 202,
  NO_CONTENT: 204,

  MOVED_PERMANENTLY: 301,
  FOUND: 302,
  NOT_MODIFIED: 304,
  TEMPORARY_REDIRECT: 307,

  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  NOT_FOUND: 404,
  CONFLICT: 409,
  UNPROCESSABLE_ENTITY: 422,
  TOO_MANY_REQUESTS: 429,

  INTERNAL_SERVER_ERROR: 500,
  NOT_IMPLEMENTED: 501,
  BAD_GATEWAY: 502,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504,
} as const;

export const HTTP_STATUS_TEXT: Record<number, string> = {
  200: 'OK',
  201: 'Created',
  202: 'Accepted',
  204: 'No Content',
  301: 'Moved Permanently',
  302: 'Found',
  304: 'Not Modified',
  307: 'Temporary Redirect',
  400: 'Bad Request',
  401: 'Unauthorized',
  403: 'Forbidden',
  404: 'Not Found',
  409: 'Conflict',
  422: 'Unprocessable Entity',
  429: 'Too Many Requests',
  500: 'Internal Server Error',
  501: 'Not Implemented',
  502: 'Bad Gateway',
  503: 'Service Unavailable',
  504: 'Gateway Timeout',
} as const;

export const ERROR_CODES = {
  INVALID_INPUT: 'ERR_INVALID_INPUT',
  MISSING_FIELD: 'ERR_MISSING_FIELD',
  INVALID_FORMAT: 'ERR_INVALID_FORMAT',

  UNAUTHORIZED: 'ERR_UNAUTHORIZED',
  INVALID_CREDENTIALS: 'ERR_INVALID_CREDENTIALS',
  TOKEN_EXPIRED: 'ERR_TOKEN_EXPIRED',
  TOKEN_INVALID: 'ERR_TOKEN_INVALID',

  FORBIDDEN: 'ERR_FORBIDDEN',
  INSUFFICIENT_PERMISSIONS: 'ERR_INSUFFICIENT_PERMISSIONS',

  NOT_FOUND: 'ERR_NOT_FOUND',
  ALREADY_EXISTS: 'ERR_ALREADY_EXISTS',
  CONFLICT: 'ERR_CONFLICT',

  TOO_MANY_REQUESTS: 'ERR_TOO_MANY_REQUESTS',

  PAYMENT_FAILED: 'ERR_PAYMENT_FAILED',
  ORDER_INVALID: 'ERR_ORDER_INVALID',
  ESIM_UNAVAILABLE: 'ERR_ESIM_UNAVAILABLE',

  EXTERNAL_API_ERROR: 'ERR_EXTERNAL_API_ERROR',
  EXTERNAL_API_TIMEOUT: 'ERR_EXTERNAL_API_TIMEOUT',

  INTERNAL_ERROR: 'ERR_INTERNAL_ERROR',
  SERVICE_UNAVAILABLE: 'ERR_SERVICE_UNAVAILABLE',
} as const;
