export const COUNTRY_CODE_TO_NAME: Record<string, string> = {
  BD: "Bangladesh",
  IN: "India",
  PK: "Pakistan",
  LK: "Sri Lanka",
  NP: "Nepal",
  BT: "Bhutan",
  MM: "Myanmar",
  TH: "Thailand",
  LA: "Laos",
  KH: "Cambodia",
  VN: "Vietnam",
  TW: "Taiwan",
  HK: "Hong Kong",
  MO: "Macau",
  CN: "China",
  JP: "Japan",
  KR: "South Korea",
  KP: "North Korea",
  MN: "Mongolia",
  SG: "Singapore",
  MY: "Malaysia",
  BN: "Brunei",
  PH: "Philippines",
  ID: "Indonesia",
  TL: "Timor-Leste",
  SA: "Saudi Arabia",
  AE: "United Arab Emirates",
  QA: "Qatar",
  BH: "Bahrain",
  KW: "Kuwait",
  OM: "Oman",
  YE: "Yemen",
  JO: "Jordan",
  LB: "Lebanon",
  SY: "Syria",
  IQ: "Iraq",
  IR: "Iran",
  AF: "Afghanistan",
  TR: "Turkey",
  IL: "Israel",
  PS: "Palestine",
  AZ: "Azerbaijan",
  UZ: "Uzbekistan",
  TM: "Turkmenistan",
  KZ: "Kazakhstan",
  KG: "Kyrgyzstan",
  TJ: "Tajikistan",
  GB: "United Kingdom",
  IE: "Ireland",
  FR: "France",
  DE: "Germany",
  IT: "Italy",
  ES: "Spain",
  PT: "Portugal",
  NL: "Netherlands",
  BE: "Belgium",
  LU: "Luxembourg",
  CH: "Switzerland",
  AT: "Austria",
  CZ: "Czech Republic",
  SK: "Slovakia",
  HU: "Hungary",
  RO: "Romania",
  BG: "Bulgaria",
  GR: "Greece",
  PL: "Poland",
  UA: "Ukraine",
  BY: "Belarus",
  RU: "Russia",
  SE: "Sweden",
  NO: "Norway",
  DK: "Denmark",
  FI: "Finland",
  EE: "Estonia",
  LV: "Latvia",
  LT: "Lithuania",
  HR: "Croatia",
  SI: "Slovenia",
  BA: "Bosnia and Herzegovina",
  RS: "Serbia",
  ME: "Montenegro",
  MK: "North Macedonia",
  AL: "Albania",
  XK: "Kosovo",
  CY: "Cyprus",
  MT: "Malta",
  SM: "San Marino",
  VA: "Vatican City",
  AD: "Andorra",
  MC: "Monaco",
  LI: "Liechtenstein",
  IS: "Iceland",
  US: "United States",
  CA: "Canada",
  MX: "Mexico",
  BR: "Brazil",
  AR: "Argentina",
  CL: "Chile",
  CO: "Colombia",
  PE: "Peru",
  VE: "Venezuela",
  EC: "Ecuador",
  BO: "Bolivia",
  PY: "Paraguay",
  UY: "Uruguay",
  GY: "Guyana",
  SR: "Suriname",
  GF: "French Guiana",
  CU: "Cuba",
  DO: "Dominican Republic",
  HT: "Haiti",
  JM: "Jamaica",
  TT: "Trinidad and Tobago",
  BS: "Bahamas",
  BB: "Barbados",
  GD: "Grenada",
  LC: "Saint Lucia",
  VC: "Saint Vincent and the Grenadines",
  KN: "Saint Kitts and Nevis",
  AG: "Antigua and Barbuda",
  DM: "Dominica",
  BZ: "Belize",
  GT: "Guatemala",
  HN: "Honduras",
  SV: "El Salvador",
  NI: "Nicaragua",
  CR: "Costa Rica",
  PA: "Panama",
  PR: "Puerto Rico",
  VI: "US Virgin Islands",
  VG: "British Virgin Islands",
  AI: "Anguilla",
  KY: "Cayman Islands",
  TK: "Turks and Caicos Islands",
  BM: "Bermuda",
  ZA: "South Africa",
  EG: "Egypt",
  NG: "Nigeria",
  KE: "Kenya",
  GH: "Ghana",
  ET: "Ethiopia",
  UG: "Uganda",
  TZ: "Tanzania",
  ZM: "Zambia",
  ZW: "Zimbabwe",
  MW: "Malawi",
  MZ: "Mozambique",
  AO: "Angola",
  BW: "Botswana",
  NA: "Namibia",
  LS: "Lesotho",
  SZ: "Eswatini",
  MG: "Madagascar",
  MU: "Mauritius",
  SC: "Seychelles",
  CV: "Cape Verde",
  SN: "Senegal",
  GM: "Gambia",
  GW: "Guinea-Bissau",
  BJ: "Benin",
  TG: "Togo",
  CI: "Côte d'Ivoire",
  LR: "Liberia",
  SL: "Sierra Leone",
  ML: "Mali",
  MR: "Mauritania",
  DZ: "Algeria",
  TN: "Tunisia",
  LY: "Libya",
  SD: "Sudan",
  SS: "South Sudan",
  ER: "Eritrea",
  DJ: "Djibouti",
  SO: "Somalia",
  RW: "Rwanda",
  BI: "Burundi",
  KM: "Comoros",
  CF: "Central African Republic",
  TD: "Chad",
  CM: "Cameroon",
  GA: "Gabon",
  CG: "Republic of the Congo",
  CD: "Democratic Republic of the Congo",
  GQ: "Equatorial Guinea",
  ST: "São Tomé and Príncipe",
  AU: "Australia",
  NZ: "New Zealand",
  FJ: "Fiji",
  PG: "Papua New Guinea",
  SB: "Solomon Islands",
  VU: "Vanuatu",
  WS: "Samoa",
  KI: "Kiribati",
  TO: "Tonga",
  PW: "Palau",
  FM: "Micronesia",
  MH: "Marshall Islands",
  NR: "Nauru",
  TV: "Tuvalu",
  PF: "French Polynesia",
  NC: "New Caledonia",
  GU: "Guam",
  MP: "Northern Mariana Islands",
  AS: "American Samoa",
  CK: "Cook Islands",
  NU: "Niue",
  EU: "European Union (Regional)",
  GL: "Global",
  RG: "Regional",
};

export const COUNTRY_NAME_TO_CODE: Record<string, string> = Object.fromEntries(
  Object.entries(COUNTRY_CODE_TO_NAME).map(([code, name]) => [
    name.toLowerCase(),
    code,
  ]),
);
export function getCountryName(countryCode: string | undefined): string {
  if (!countryCode) return "Unknown";
  return COUNTRY_CODE_TO_NAME[countryCode.toUpperCase()] || countryCode;
}
export function getCountryCode(countryName: string | undefined): string | null {
  if (!countryName) return null;
  return COUNTRY_NAME_TO_CODE[countryName.toLowerCase()] || null;
}
export function getAllCountries(): Array<{ code: string; name: string }> {
  return Object.entries(COUNTRY_CODE_TO_NAME)
    .map(([code, name]) => ({ code, name }))
    .sort((a, b) => a.name.localeCompare(b.name));
}
export function searchCountries(
  query: string,
): Array<{ code: string; name: string }> {
  const lowerQuery = query.toLowerCase();
  return getAllCountries().filter(
    (country) =>
      country.name.toLowerCase().includes(lowerQuery) ||
      country.code.toLowerCase().includes(lowerQuery),
  );
}
